# Generated by Django 4.0.4 on 2022-05-20 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('movie_name', models.CharField(help_text='Enter Movie', max_length=40)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('Actorname', models.CharField(help_text='Enter Actors name', max_length=25)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
